version: "3.8"

services:

  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=facts
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  app:
    build: .
    command: bash -c "uvicorn core.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/facts
      - SECRET_KEY=123abc
    volumes:
      - .:/core
    ports:
      - 8000:8000
    depends_on:
      - db
